
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'tblUsers')
BEGIN
CREATE TABLE dbo.tblUsers
	(
	ID int NOT NULL IDENTITY (1, 1),
	UserName nvarchar(50) NOT NULL,
	Password nvarchar(50) NOT NULL,
	FullName nvarchar(150) NULL,
	GroupId int NULL
	)  ON [PRIMARY]
ALTER TABLE dbo.tblUsers ADD CONSTRAINT
	PK_tblUsers PRIMARY KEY CLUSTERED 
	(
	ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

ALTER TABLE dbo.tblUsers SET (LOCK_ESCALATION = TABLE)

END
GO